# Generated by Django 5.2.8 on 2025-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from students', max_digits=3),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='Total number of ratings received'),
        ),
    ]
