# Generated by Django 5.2.7 on 2025-10-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoutprediction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='dropoutprediction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropout_predictions', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='performancetrends',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='learninganalytics',
            unique_together={('student', 'course', 'date')},
        ),
    ]
