# Generated by Django 5.2.8 on 2025-11-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseenrollment_approval_fields'),
        ('students', '0001_initial'),
        ('teachers', '0003_teacherprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, help_text='Final percentage score', max_digits=5)),
                ('letter_grade', models.CharField(help_text='A, B, C, D, F, etc.', max_length=5)),
                ('grade_points', models.DecimalField(decimal_places=2, help_text='GPA points (4.0 scale)', max_digits=3)),
                ('assignments_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quizzes_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exams_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('projects_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('participation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5')),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback from student')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible_to_teacher', models.BooleanField(default=True)),
                ('is_visible_to_admin', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher_ratings',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='courseenrollment',
            name='unique_student_course',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_instruc_680c73_idx',
            old_name='courses_inst_status_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_subject_5549aa_idx',
            old_name='courses_subj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='course_enro_student_8023bd_idx',
            old_name='enrollments_student_status_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='course_enro_course__37db5f_idx',
            old_name='enrollments_course_status_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_assigned', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherrating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ratings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacherrating',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rating', to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='teacherrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ratings', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='teacherrating',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='teachers.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'is_published'], name='grades_student_acc642_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['teacher', 'course'], name='grades_teacher_717520_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'course', 'student')},
        ),
        migrations.AddIndex(
            model_name='teacherrating',
            index=models.Index(fields=['teacher', 'rating'], name='teacher_rat_teacher_91c7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherrating',
            index=models.Index(fields=['course'], name='teacher_rat_course__cfc53a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherrating',
            unique_together={('student', 'teacher', 'course')},
        ),
    ]
