# Generated by Django 5.2.8 on 2025-11-13 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_grade_teacherrating_and_more'),
        ('students', '0001_initial'),
        ('teachers', '0003_teacherprofile_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('enrollment_request', 'Enrollment Request'), ('enrollment_approval', 'Enrollment Approval'), ('enrollment_rejection', 'Enrollment Rejection'), ('grade_submission', 'Grade Submission'), ('grade_update', 'Grade Update'), ('grade_publish', 'Grade Publish'), ('feedback_generation', 'Feedback Generation'), ('certificate_generation', 'Certificate Generation'), ('course_creation', 'Course Creation'), ('course_update', 'Course Update'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('ai_access', 'AI Feature Access'), ('rating_submission', 'Rating Submission')], max_length=50)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='activity_lo_user_id_e40ffe_idx'), models.Index(fields=['action_type', 'timestamp'], name='activity_lo_action__4f011a_idx'), models.Index(fields=['target_model', 'target_id'], name='activity_lo_target__23e139_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('final_grade', models.CharField(max_length=5)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verification_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.courseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates_issued', to='teachers.teacherprofile')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['student', 'issue_date'], name='certificate_student_784da1_idx'), models.Index(fields=['certificate_id'], name='certificate_certifi_a0a669_idx'), models.Index(fields=['verification_code'], name='certificate_verific_8df4b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('submission_graded', 'Submission Graded'), ('grade_published', 'Grade Published'), ('certificate_ready', 'Certificate Ready'), ('ai_feedback_ready', 'AI Feedback Ready'), ('course_update', 'Course Update'), ('system_alert', 'System Alert'), ('teacher_message', 'Teacher Message'), ('assignment_due', 'Assignment Due')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('predicted_next_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('suggested_modules', models.JSONField(blank=True, default=list)),
                ('estimated_improvement_time', models.DurationField(blank=True, null=True)),
                ('ai_model_version', models.CharField(default='gemini-pro', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.85, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.courseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='students.studentprofile')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='courses.assignmentsubmission')),
            ],
            options={
                'db_table': 'student_feedbacks',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'generated_at'], name='student_fee_student_9973c9_idx'), models.Index(fields=['enrollment'], name='student_fee_enrollm_236dd9_idx')],
            },
        ),
    ]
