# Generated by Django 5.2.8 on 2025-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_activitylog_certificate_notification_studentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ai_content_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
