# Generated by Django 5.2.7 on 2025-10-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='related_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='userinteractionpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_patterns', to=settings.AUTH_USER_MODEL),
        ),
    ]
