# Generated by Django 5.2.7 on 2025-10-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_technical', models.BooleanField(default=True)),
                ('market_demand', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('ai_optimized', models.BooleanField(default=False)),
                ('optimization_suggestions', models.JSONField(default=list)),
                ('ats_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='students.studentprofile')),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='JobMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead/Manager')], max_length=15)),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_demand', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('growth_projection', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('automation_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('preferred_skills', models.ManyToManyField(related_name='preferred_for_jobs', to='career.skill')),
                ('required_skills', models.ManyToManyField(related_name='required_for_jobs', to='career.skill')),
            ],
            options={
                'db_table': 'job_market_data',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.skillcategory')),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'skill_categories',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='career.skillcategory'),
        ),
        migrations.CreateModel(
            name='StudentSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=15)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('verified', models.BooleanField(default=False)),
                ('acquisition_date', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('practice_hours', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.skill')),
            ],
            options={
                'db_table': 'student_skill_levels',
            },
        ),
        migrations.CreateModel(
            name='StudentSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_gaps', models.JSONField(default=list)),
                ('recommended_skills', models.JSONField(default=list)),
                ('career_recommendations', models.JSONField(default=list)),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(through='career.StudentSkillLevel', to='career.skill')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to='students.studentprofile')),
            ],
            options={
                'db_table': 'student_skill_profiles',
            },
        ),
        migrations.AddField(
            model_name='studentskilllevel',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.studentskillprofile'),
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('provider', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('certification_offered', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_skills', models.ManyToManyField(related_name='training_programs', to='career.skill')),
            ],
            options={
                'db_table': 'training_programs',
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_match_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_match', models.BooleanField()),
                ('location_preference_match', models.BooleanField(default=True)),
                ('recommendation_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('reasons', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('preparation_suggestions', models.JSONField(default=list)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.jobmarketdata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='students.studentprofile')),
            ],
            options={
                'db_table': 'job_recommendations',
                'unique_together': {('student', 'job_data')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentskilllevel',
            unique_together={('student_profile', 'skill')},
        ),
    ]
