# Generated by Django 5.2.7 on 2025-10-19 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='certifications',
            new_name='suggestions',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='JobMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('match_score', models.IntegerField()),
                ('requirements_met', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('salary_range', models.JSONField(default=dict)),
                ('location', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('application_deadline', models.DateTimeField()),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='students.studentprofile')),
            ],
            options={
                'db_table': 'job_matchings',
            },
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('education_level', models.CharField(default='Bachelor', max_length=50)),
                ('preferred_job_types', models.JSONField(default=list)),
                ('location_preference', models.CharField(default='', max_length=100)),
                ('salary_expectation', models.IntegerField(default=0)),
                ('work_experience', models.JSONField(default=list)),
                ('achievements', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resume_profiles',
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.JSONField(default=dict)),
                ('soft_skills', models.JSONField(default=dict)),
                ('overall_score', models.IntegerField(default=0)),
                ('assessment_date', models.DateTimeField(blank=True, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('areas_for_improvement', models.JSONField(default=list)),
                ('career_recommendations', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_assessments',
            },
        ),
    ]
